apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongodb
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: admin
          - name: MONGO_NON_ROOT_USERNAME
            value: newuser
          - name: MONGO_NON_ROOT_PASSWORD
            value: secret
          - name: MONGO_INITDB_DATABASE
            value: mydatabase
        volumeMounts:
          - name: initfile
            mountPath: /docker-entrypoint-initdb.d
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: initfile
          configMap:
            name: initfile
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo